spring:
  profiles:
    active:
    - default
  application:
    name: tvajjala.in
  output:
    ansi:
      enabled: always
logging:
  level:
    # Enabling trace for app specific logging.
    com.tvajjala: DEBUG
    org.springframework: INFO
